using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CashOut.Data.Migrations
{
    /// <inheritdoc />
    public partial class MerchantNormalization : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Every DDL step is wrapped in an existence check so the migration is safe
            // to re-run after a partial failure from a previous attempt.

            // ── alias_patterns ────────────────────────────────────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS alias_patterns (
                    ""Id""        integer GENERATED BY DEFAULT AS IDENTITY,
                    ""AliasId""   integer NOT NULL,
                    ""Pattern""   text NOT NULL,
                    ""MatchType"" text NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    ""UpdatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_alias_patterns"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_alias_patterns_business_aliases_AliasId""
                        FOREIGN KEY (""AliasId"") REFERENCES business_aliases (""Id"") ON DELETE CASCADE
                )");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_alias_patterns_AliasId""
                ON alias_patterns (""AliasId"")");

            // ── raw_businesses — CategoryRaw ──────────────────────────────
            migrationBuilder.Sql(@"
                ALTER TABLE raw_businesses
                ADD COLUMN IF NOT EXISTS ""CategoryRaw"" text NOT NULL DEFAULT ''");

            // Copy existing Category into CategoryRaw for rows where CategoryRaw is still empty.
            // Safe to run repeatedly.
            migrationBuilder.Sql(@"
                UPDATE raw_businesses
                SET ""CategoryRaw"" = COALESCE(""Category"", '')
                WHERE ""CategoryRaw"" = '' AND ""Category"" IS NOT NULL");

            // ── raw_businesses — IsMapped ─────────────────────────────────
            migrationBuilder.Sql(@"
                ALTER TABLE raw_businesses
                ADD COLUMN IF NOT EXISTS ""IsMapped"" boolean NOT NULL DEFAULT false");

            migrationBuilder.Sql(@"
                UPDATE raw_businesses rb
                SET ""IsMapped"" = true
                WHERE EXISTS (
                    SELECT 1 FROM raw_business_alias_map m
                    WHERE m.""RawBusinessId"" = rb.""Id""
                )");

            // ── raw_businesses — RawNameNormalized ────────────────────────
            migrationBuilder.Sql(@"
                ALTER TABLE raw_businesses
                ADD COLUMN IF NOT EXISTS ""RawNameNormalized"" text NOT NULL DEFAULT ''");

            // Populate RawNameNormalized for rows that still have the empty default.
            // The expression mirrors the C# Normalize() pipeline:
            //   trim → collapse spaces → uppercase → strip punctuation → collapse spaces
            //   → strip numeric sequences > 6 digits → final trim.
            migrationBuilder.Sql(@"
                UPDATE raw_businesses SET ""RawNameNormalized"" =
                    TRIM(
                        regexp_replace(
                            regexp_replace(
                                UPPER(
                                    regexp_replace(
                                        regexp_replace(TRIM(""RawName""), '\s+', ' ', 'g'),
                                        '[-*./:]', ' ', 'g'
                                    )
                                ),
                                '\s+', ' ', 'g'
                            ),
                            '\m\d{7,}\M', '', 'g'
                        )
                    )
                WHERE ""RawNameNormalized"" = ''");

            // Ensure no empty strings remain (e.g. RawName was blank).
            migrationBuilder.Sql(@"
                UPDATE raw_businesses
                SET ""RawNameNormalized"" = 'UNKNOWN#' || ""Id""::text
                WHERE TRIM(""RawNameNormalized"") = ''");

            // Deduplicate: keep the row with the lowest Id, suffix the rest.
            // Runs in a loop until no duplicates remain (handles chains of 3+).
            migrationBuilder.Sql(@"
                DO $$
                DECLARE v_count int;
                BEGIN
                    LOOP
                        UPDATE raw_businesses rb
                        SET ""RawNameNormalized"" = rb.""RawNameNormalized"" || '#' || rb.""Id""::text
                        WHERE rb.""Id"" NOT IN (
                            SELECT MIN(""Id"") FROM raw_businesses GROUP BY ""RawNameNormalized""
                        )
                        AND EXISTS (
                            SELECT 1 FROM raw_businesses rb2
                            WHERE rb2.""RawNameNormalized"" = rb.""RawNameNormalized""
                              AND rb2.""Id"" <> rb.""Id""
                        );
                        GET DIAGNOSTICS v_count = ROW_COUNT;
                        EXIT WHEN v_count = 0;
                    END LOOP;
                END $$");

            // ── Unique index on RawNameNormalized ─────────────────────────
            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_raw_businesses_RawNameNormalized""
                ON raw_businesses (""RawNameNormalized"")");

            // ── Drop old Category column ──────────────────────────────────
            // Guard: only drop if it still exists (previous partial run may have left it).
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'raw_businesses' AND column_name = 'Category'
                    ) THEN
                        ALTER TABLE raw_businesses DROP COLUMN ""Category"";
                    END IF;
                END $$");

            // ── Drop old RawName unique index ─────────────────────────────
            migrationBuilder.Sql(@"
                DROP INDEX IF EXISTS ""IX_raw_businesses_RawName""");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "alias_patterns");

            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_raw_businesses_RawNameNormalized""");

            migrationBuilder.AddColumn<string>(
                name: "Category",
                table: "raw_businesses",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.Sql(@"UPDATE raw_businesses SET ""Category"" = ""CategoryRaw""");

            migrationBuilder.DropColumn(name: "CategoryRaw", table: "raw_businesses");
            migrationBuilder.DropColumn(name: "RawNameNormalized", table: "raw_businesses");
            migrationBuilder.DropColumn(name: "IsMapped", table: "raw_businesses");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_raw_businesses_RawName""
                ON raw_businesses (""RawName"")");
        }
    }
}